### ISSUE TITLE
Repo seems to be unmaintained

### ISSUE THREAD

**Issue by enpitsuLin** [brechtcs/hast-util-class-list#2]
Sorry to disturb you, but please allow me to use the mention here. @brechtcs  

This repo seems to be unmaintained, but I'm interested in maintaining this package

Currently, I have done some thing in closed PR (but forked repo is deleted)
- rewrite using the ES6 syntax
- better simulation of [`classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) api with class syntax
- add type definition allows TS projects to use this package more easily

**Comment by brechtcs** [comment]
It's not unmaintained, it's considered feature complete. If you've found  any bugs or want to propose improvements, you're always welcome to open separate issues and PRs.
